version: '3'

services:

  database:
    container_name: mysql
    image: mysql/mysql-server:8.0.23
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: cursogo
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3307:3306
    expose:
      - 3307
    volumes:
      - cursogo-data:/var/lib/mysql


# persisted storage
volumes:
  cursogo-data: